version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=tobi
      - RABBITMQ_DEFAULT_PASS=0191
    ports:
      - 5672:5672
      - 15672:15672
