version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5532:5532
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "0191"
      POSTGRES_DB: "book"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /infrastructures/pgdata:/var/lib/postgresql/data \